//! Set / rotate and revoke a developer credential (Go
//! `SetDeveloperCredential`, `RevokeDeveloperCredential`). The handler has
//! already applied the caller's authority (self, or a user admin in scope);
//! these check the target and commit through the unit of work.

use std::sync::Arc;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use super::events::{DeveloperCredentialRevoked, DeveloperCredentialSet};
use super::{DeveloperCredential, DEVELOPER_ROLE};
use crate::usecase::{
    ExecutionContext, OrNotFound, UnitOfWork, UseCase, UseCaseError, UseCaseResult,
};
use crate::PrincipalRepository;

/// Set or rotate `principal_id`'s developer secret to `secret_ref` (the
/// keyed hash; generated by the handler, which answers the plaintext once).
/// The audit row records `{principalId}` only.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SetDeveloperCredentialCommand {
    pub principal_id: String,
    #[serde(skip)]
    pub secret_ref: String,
}

impl crate::usecase::AuditMasked for SetDeveloperCredentialCommand {}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RevokeDeveloperCredentialCommand {
    pub principal_id: String,
}

impl crate::usecase::AuditMasked for RevokeDeveloperCredentialCommand {}

fn require_id(id: &str) -> Result<(), UseCaseError> {
    if id.trim().is_empty() {
        return Err(UseCaseError::validation(
            "PRINCIPAL_ID_REQUIRED",
            "Principal ID is required",
        ));
    }
    Ok(())
}

pub struct SetDeveloperCredentialUseCase<U: UnitOfWork> {
    pub principal_repo: Arc<PrincipalRepository>,
    pub unit_of_work: Arc<U>,
}

#[async_trait]
impl<U: UnitOfWork> UseCase for SetDeveloperCredentialUseCase<U> {
    type Command = SetDeveloperCredentialCommand;
    type Event = DeveloperCredentialSet;

    async fn validate(&self, command: &Self::Command) -> Result<(), UseCaseError> {
        require_id(&command.principal_id)
    }

    async fn authorize(
        &self,
        _command: &Self::Command,
        _ctx: &ExecutionContext,
    ) -> Result<(), UseCaseError> {
        Ok(())
    }

    async fn execute(
        &self,
        command: Self::Command,
        ctx: ExecutionContext,
    ) -> UseCaseResult<Self::Event> {
        let principal = match self
            .principal_repo
            .find_by_id(&command.principal_id)
            .await
            .or_not_found(
                "USER_NOT_FOUND",
                format!("User '{}' not found", command.principal_id),
            ) {
            Ok(p) => p,
            Err(e) => return UseCaseResult::failure(e),
        };
        if !principal.is_user() {
            return UseCaseResult::failure(UseCaseError::business_rule(
                "NOT_A_USER",
                "Developer credentials can only be set on USER type principals",
            ));
        }
        if !principal.roles.iter().any(|r| r.role == DEVELOPER_ROLE) {
            return UseCaseResult::failure(UseCaseError::business_rule(
                "NOT_A_DEVELOPER",
                "Principal does not hold the developer role",
            ));
        }
        let credential = DeveloperCredential {
            principal_id: principal.id.clone(),
            secret_ref: Some(command.secret_ref.clone()),
        };
        let event = DeveloperCredentialSet::new(&ctx, &principal.id);
        self.unit_of_work
            .commit(&credential, &*self.principal_repo, event, &command)
            .await
    }
}

pub struct RevokeDeveloperCredentialUseCase<U: UnitOfWork> {
    pub principal_repo: Arc<PrincipalRepository>,
    pub unit_of_work: Arc<U>,
}

#[async_trait]
impl<U: UnitOfWork> UseCase for RevokeDeveloperCredentialUseCase<U> {
    type Command = RevokeDeveloperCredentialCommand;
    type Event = DeveloperCredentialRevoked;

    async fn validate(&self, command: &Self::Command) -> Result<(), UseCaseError> {
        require_id(&command.principal_id)
    }

    async fn authorize(
        &self,
        _command: &Self::Command,
        _ctx: &ExecutionContext,
    ) -> Result<(), UseCaseError> {
        Ok(())
    }

    async fn execute(
        &self,
        command: Self::Command,
        ctx: ExecutionContext,
    ) -> UseCaseResult<Self::Event> {
        let principal = match self
            .principal_repo
            .find_by_id(&command.principal_id)
            .await
            .or_not_found(
                "USER_NOT_FOUND",
                format!("User '{}' not found", command.principal_id),
            ) {
            Ok(p) => p,
            Err(e) => return UseCaseResult::failure(e),
        };
        let credential = DeveloperCredential {
            principal_id: principal.id.clone(),
            secret_ref: None,
        };
        let event = DeveloperCredentialRevoked::new(&ctx, &principal.id);
        self.unit_of_work
            .commit_delete(&credential, &*self.principal_repo, event, &command)
            .await
    }
}
