[package]
name = "fc-stream"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fc-common = { path = "../fc-common", features = ["dispatch-lifecycle"] }
tokio = { workspace = true }
tokio-util = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "macros", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
