package io.flowcatalyst.function;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Map;

/// The `function-api` half of `GoldenGen`: `Webhook.event` / `Webhook.schedule`
/// (including `Instant.parse` and `Integer.parseInt` on the wire values) and
/// `Result.fail`'s escaping, written as tables of Java's real answers.
public final class WebhookGolden {

    private static final Base64.Encoder B64 = Base64.getEncoder();

    private WebhookGolden() {
    }

    public static void write(Path out) throws IOException {
        eventTable(out.resolve("webhook-event.tsv"));
        scheduleTable(out.resolve("webhook-schedule.tsv"));
        failTable(out.resolve("result-fail.tsv"));
    }

    private static Request request(byte[] body) {
        return new Request(FunctionAddress.parse("billing.invoices.api"), 1, "invocation-1", "POST", "/e", null,
                null, Map.of(), Map.of(), Map.of(), body, "10.0.0.1", Caller.Platform.INSTANCE);
    }

    private static String enc(String s) {
        return s == null ? "~" : B64.encodeToString(s.getBytes(StandardCharsets.UTF_8));
    }

    private static final String HEADER =
            "# Generated by tests/java/.../GoldenGen.java. Do not edit.\n"
                    + "# name\\tbody(b64)\\tOK\\tfields ('~' = null, strings b64, instants epochSecond.nano)"
                    + "  |  name\\tbody(b64)\\tERR\\tmessage\n";

    private static void eventTable(Path file) throws IOException {
        List<String[]> rows = new ArrayList<>();
        rows.add(new String[] {"full", "{\"id\":\"djb_123\",\"type\":\"billing:invoices:invoice:created\",\"attemptNumber\":2,"
                + "\"source\":\"billing-service\",\"subject\":\"inv_1\",\"correlationId\":\"corr-1\","
                + "\"messageGroup\":\"group-1\",\"clientId\":\"cli_1\",\"clientCode\":\"acme\","
                + "\"data\":{\"invoiceId\":\"inv_1\",\"amount\":100}}"});
        rows.add(new String[] {"minimal", "{\"id\":\"djb_1\",\"type\":\"t\",\"attemptNumber\":1}"});
        rows.add(new String[] {"data string", "{\"id\":\"djb_1\",\"type\":\"t\",\"attemptNumber\":1,\"data\":\"not json {\"}"});
        rows.add(new String[] {"data raw kept verbatim", " { \"data\" : { \"x\": 1,  \"y\":[1,2] , \"s\":\"\\u00e9\\ud800\" } ,\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1 } "});
        rows.add(new String[] {"data null", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"data\":null}"});
        rows.add(new String[] {"data number", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"data\":-1.5e3}"});
        rows.add(new String[] {"data false", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"data\":false}"});
        rows.add(new String[] {"optional null", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"source\":null,\"clientId\":null}"});
        rows.add(new String[] {"optional wrong type", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"source\":5}"});
        rows.add(new String[] {"no id", "{\"type\":\"t\",\"attemptNumber\":1}"});
        rows.add(new String[] {"no type", "{\"id\":\"i\",\"attemptNumber\":1}"});
        rows.add(new String[] {"no attemptNumber", "{\"id\":\"i\",\"type\":\"t\"}"});
        rows.add(new String[] {"id null", "{\"id\":null,\"type\":\"t\",\"attemptNumber\":1}"});
        rows.add(new String[] {"id number", "{\"id\":1,\"type\":\"t\",\"attemptNumber\":1}"});
        rows.add(new String[] {"attempt string", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":\"1\"}"});
        rows.add(new String[] {"attempt fraction", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1.5}"});
        rows.add(new String[] {"attempt 1.0", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1.0}"});
        rows.add(new String[] {"attempt exponent", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1e0}"});
        rows.add(new String[] {"attempt negative zero", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":-0}"});
        rows.add(new String[] {"attempt negative", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":-7}"});
        rows.add(new String[] {"attempt int max", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":2147483647}"});
        rows.add(new String[] {"attempt int overflow", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":2147483648}"});
        rows.add(new String[] {"attempt int min", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":-2147483648}"});
        rows.add(new String[] {"duplicate key", "{\"id\":\"i\",\"id\":\"j\",\"type\":\"t\",\"attemptNumber\":1}"});
        rows.add(new String[] {"duplicate unknown key", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"z\":1,\"z\":2}"});
        rows.add(new String[] {"unknown keys ignored", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"extra\":{\"deep\":[1]}}"});
        rows.add(new String[] {"lone surrogate in id", "{\"id\":\"a\\ud800b\",\"type\":\"t\",\"attemptNumber\":1}"});
        rows.add(new String[] {"surrogate pair in id", "{\"id\":\"\\ud83d\\ude00\",\"type\":\"😀\",\"attemptNumber\":1}"});
        rows.add(new String[] {"escapes in id", "{\"id\":\"a\\\"\\\\\\/\\b\\f\\n\\r\\t\\u0041\",\"type\":\"t\",\"attemptNumber\":1}"});
        rows.add(new String[] {"array", "[1,2,3]"});
        rows.add(new String[] {"not json", "not json"});
        rows.add(new String[] {"empty", ""});
        rows.add(new String[] {"string", "\"x\""});
        rows.add(new String[] {"trailing garbage", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1} x"});
        rows.add(new String[] {"utf-8 bom", "﻿{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1}"});
        rows.add(new String[] {"vertical tab whitespace", "{\u000B\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1}"});
        rows.add(new String[] {"depth 64 in data", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"data\":" + "[".repeat(63) + "]".repeat(63) + "}"});
        rows.add(new String[] {"depth 65 in data", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"data\":" + "[".repeat(64) + "]".repeat(64) + "}"});
        rows.add(new String[] {"depth 66 in data", "{\"id\":\"i\",\"type\":\"t\",\"attemptNumber\":1,\"data\":" + "[".repeat(65) + "]".repeat(65) + "}"});
        List<byte[]> bodies = new ArrayList<>();
        for (String[] r : rows) bodies.add(r[1].getBytes(StandardCharsets.UTF_8));
        rows.add(new String[] {"invalid utf-8 in id", null});
        bodies.add(concat("{\"id\":\"a", new byte[] {(byte) 0xff, (byte) 0xe2, (byte) 0x82, 'b'}, "\",\"type\":\"t\",\"attemptNumber\":1}"));
        rows.add(new String[] {"truncated utf-8 in id", null});
        bodies.add(concat("{\"id\":\"a", new byte[] {(byte) 0xf0, (byte) 0x9f, (byte) 0x98}, "\",\"type\":\"t\",\"attemptNumber\":1}"));
        rows.add(new String[] {"overlong utf-8 in id", null});
        bodies.add(concat("{\"id\":\"a", new byte[] {(byte) 0xc0, (byte) 0xaf, (byte) 0xed, (byte) 0xa0, (byte) 0x80}, "\",\"type\":\"t\",\"attemptNumber\":1}"));

        byte[][] extra = {
                {(byte) 0xc3, (byte) 0xa9}, {(byte) 0xc0, (byte) 0xaf}, {(byte) 0xc1, (byte) 0xbf}, {(byte) 0xc2},
                {(byte) 0xc2, 'x'}, {(byte) 0xe0, (byte) 0x80, (byte) 0x80}, {(byte) 0xe0, (byte) 0xa0, (byte) 0x80},
                {(byte) 0xe0, (byte) 0x9f, (byte) 0xbf}, {(byte) 0xed, (byte) 0x9f, (byte) 0xbf},
                {(byte) 0xed, (byte) 0xa0, (byte) 0x80}, {(byte) 0xed, (byte) 0xbf, (byte) 0xbf}, {(byte) 0xe2, 'x'},
                {(byte) 0xe2, (byte) 0x82, 'x'}, {(byte) 0xef, (byte) 0xbf, (byte) 0xbf},
                {(byte) 0xf0, (byte) 0x80, (byte) 0x80, (byte) 0x80}, {(byte) 0xf0, (byte) 0x90, (byte) 0x80, (byte) 0x80},
                {(byte) 0xf0, (byte) 0x8f, (byte) 0xbf, (byte) 0xbf}, {(byte) 0xf4, (byte) 0x8f, (byte) 0xbf, (byte) 0xbf},
                {(byte) 0xf4, (byte) 0x90, (byte) 0x80, (byte) 0x80}, {(byte) 0xf5, (byte) 0x80, (byte) 0x80, (byte) 0x80},
                {(byte) 0xf7, (byte) 0xbf, (byte) 0xbf, (byte) 0xbf}, {(byte) 0xf8, (byte) 0x88, (byte) 0x80, (byte) 0x80, (byte) 0x80},
                {(byte) 0xf0, (byte) 0x9f, 'x'}, {(byte) 0xf0, (byte) 0x9f, (byte) 0x98, 'x'}, {(byte) 0xf0, 'x'},
                {(byte) 0xf4, (byte) 0x90, 'x'}, {(byte) 0x80, (byte) 0xbf}, {(byte) 0xfe, (byte) 0xff},
        };
        for (byte[] bad : extra) {
            StringBuilder n = new StringBuilder("utf-8");
            for (byte b : bad) n.append(String.format(" %02x", b & 0xff));
            rows.add(new String[] {n.toString(), null});
            bodies.add(concat("{\"id\":\"<", bad, ">\",\"type\":\"t\",\"attemptNumber\":1}"));
        }
        // truncated sequences at the very end of the body (the decoder's own end-of-input paths)
        byte[][] tails = {
                {(byte) 0xc3}, {(byte) 0xe2}, {(byte) 0xe2, (byte) 0x82}, {(byte) 0xe0, (byte) 0x80}, {(byte) 0xf0},
                {(byte) 0xf0, (byte) 0x9f}, {(byte) 0xf0, (byte) 0x9f, (byte) 0x98}, {(byte) 0xf0, (byte) 0x80},
                {(byte) 0xf5, (byte) 0x80}, {(byte) 0xf0, (byte) 0x9f, 'x'}, {(byte) 0xe2, 'x'},
        };
        for (byte[] bad : tails) {
            StringBuilder n = new StringBuilder("utf-8 at end");
            for (byte b : bad) n.append(String.format(" %02x", b & 0xff));
            rows.add(new String[] {n.toString(), null});
            bodies.add(concat("\"", bad, ""));
        }

        StringBuilder sb = new StringBuilder(HEADER);
        for (int i = 0; i < rows.size(); i++) {
            byte[] body = bodies.get(i);
            sb.append(rows.get(i)[0]).append('\t').append(B64.encodeToString(body)).append('\t');
            try {
                Event e = Webhook.event(request(body));
                sb.append("OK\t").append(String.join(",", enc(e.id()), enc(e.type()), Integer.toString(e.attemptNumber()),
                        enc(e.source()), enc(e.subject()), enc(e.correlationId()), enc(e.messageGroup()),
                        enc(e.clientId()), enc(e.clientCode()), enc(e.dataJson())));
            } catch (WebhookFormatException ex) {
                sb.append("ERR\t").append(ex.getMessage().replace('\n', ' ').replace('\t', ' '));
            }
            sb.append('\n');
        }
        Files.writeString(file, sb.toString());
    }

    private static String inst(Instant i) {
        return i == null ? "~" : i.getEpochSecond() + "." + i.getNano();
    }

    private static void scheduleTable(Path file) throws IOException {
        List<String[]> rows = new ArrayList<>();
        String rest = ",\"triggerKind\":\"CRON\",\"tracksCompletion\":true,\"concurrent\":false}";
        String head = "{\"jobId\":\"sjb_1\",\"jobCode\":\"nightly-report\",\"instanceId\":\"sji_1\",";
        rows.add(new String[] {"full", "{\"jobId\":\"sjb_1\",\"jobCode\":\"nightly-report\",\"instanceId\":\"sji_1\","
                + "\"scheduledFor\":\"2026-09-19T00:00:00.000000Z\",\"firedAt\":\"2026-09-19T00:00:01.500000Z\","
                + "\"triggerKind\":\"CRON\",\"correlationId\":\"corr-9\",\"payload\":{\"n\":1},"
                + "\"tracksCompletion\":true,\"timeoutSeconds\":30,\"concurrent\":false}"});
        rows.add(new String[] {"minimal", "{\"jobId\":\"sjb_1\",\"jobCode\":\"nightly-report\",\"instanceId\":\"sji_1\","
                + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"triggerKind\":\"MANUAL\",\"tracksCompletion\":false,\"concurrent\":true}"});
        rows.add(new String[] {"unknown trigger kind kept", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"triggerKind\":\"SOMETHING_NEW\",\"tracksCompletion\":false,\"concurrent\":true}"});
        rows.add(new String[] {"no jobId", "{\"jobCode\":\"c\",\"instanceId\":\"i\",\"firedAt\":\"2026-09-19T00:00:00Z\"" + rest});
        rows.add(new String[] {"no firedAt", "{\"jobId\":\"j\",\"jobCode\":\"c\",\"instanceId\":\"i\"" + rest});
        rows.add(new String[] {"bad firedAt", "{\"jobId\":\"j\",\"jobCode\":\"c\",\"instanceId\":\"i\",\"firedAt\":\"not-a-time\"" + rest});
        rows.add(new String[] {"tracksCompletion string", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"triggerKind\":\"CRON\",\"tracksCompletion\":\"true\",\"concurrent\":true}"});
        rows.add(new String[] {"concurrent missing", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"triggerKind\":\"CRON\",\"tracksCompletion\":true}"});
        rows.add(new String[] {"triggerKind number", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"triggerKind\":1,\"tracksCompletion\":true,\"concurrent\":true}"});
        rows.add(new String[] {"timeout null", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"timeoutSeconds\":null" + rest});
        rows.add(new String[] {"timeout fraction", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"timeoutSeconds\":1.5" + rest});
        rows.add(new String[] {"timeout string", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"timeoutSeconds\":\"30\"" + rest});
        rows.add(new String[] {"scheduledFor null", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"scheduledFor\":null" + rest});
        rows.add(new String[] {"scheduledFor bad", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"scheduledFor\":\"x\"" + rest});
        rows.add(new String[] {"scheduledFor number", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"scheduledFor\":5" + rest});
        rows.add(new String[] {"payload array", head + "\"firedAt\":\"2026-09-19T00:00:01Z\",\"payload\":[ 1 ,2 ]" + rest});
        for (String ts : List.of(
                "2026-09-19T00:00:00Z", "2026-09-19T00:00:00.000000Z", "2026-09-19T00:00:01.5Z",
                "2026-09-19T00:00:00.123456789Z", "2026-09-19T00:00:00.1234567890Z", "2026-09-19T00:00:00.Z",
                "2026-09-19t00:00:00z", "2026-09-19T00:00:00+01:00", "2026-09-19T00:00:00-01:30",
                "2026-09-19T00:00:00+01:00:30", "2026-09-19T00:00:00+0100", "2026-09-19T00:00:00+01",
                "2026-09-19T00:00:00+00:00", "2026-09-19T00:00:00-00:00", "2026-09-19T00:00:00+18:00",
                "2026-09-19T00:00:00+19:00", "2026-09-19T00:00:00+01:60", "2026-09-19T00:00:00+00:00:00",
                "2026-09-19T00:00:00UTC", "2026-09-19T00:00:00Z[UTC]", "2026-09-19T00:00Z", "2026-09-19T00:00:00",
                "2026-09-19 00:00:00Z", "2026-09-19T24:00:00Z", "2026-09-19T24:00:01Z", "2026-09-19T23:59:60Z",
                "2026-09-19T12:59:60Z", "2026-09-19T25:00:00Z", "2026-09-19T00:60:00Z", "2024-02-29T00:00:00Z",
                "2026-02-29T00:00:00Z", "2026-13-01T00:00:00Z", "2026-00-01T00:00:00Z", "2026-04-31T00:00:00Z",
                "2026-9-19T00:00:00Z", "+12026-09-19T00:00:00Z", "12026-09-19T00:00:00Z", "-0001-01-01T00:00:00Z",
                "0000-01-01T00:00:00Z", "+2026-09-19T00:00:00Z", "-2026-09-19T00:00:00Z",
                "+999999999-12-31T23:59:59Z", "+1000000000-01-01T00:00:00Z", "-999999999-01-01T00:00:00Z",
                "2026-09-19T00:00:00.5+05:30", "1970-01-01T00:00:00Z", "1969-12-31T23:59:59.999999999Z",
                " 2026-09-19T00:00:00Z", "2026-09-19T00:00:00Z ", "2026-09-19T00:00:00.123Z",
                "2026-09-19T1:00:00Z", "2026-09-19T00:00:00+1:00", "2026-09-19T00:00:00+01:0",
                "2026-09-19T00:00:00-18:00", "2026-09-19T00:00:00+18:00:01", "2026-09-19T00:00:00+17:59:59",
                "2026-09-19T00:00:00+05:30:60", "2026-09-19T23:59:60.5Z", "2026-12-31T24:00:00Z",
                "2026-09-19T00:00:00.000000000Z", "2026-09-19T00:00:00,5Z", "2026-09-19T00:00:00.-5Z")) {
            rows.add(new String[] {"ts " + ts, head + "\"firedAt\":\"" + ts + "\"" + rest});
        }

        StringBuilder sb = new StringBuilder(HEADER);
        for (String[] r : rows) {
            byte[] body = r[1].getBytes(StandardCharsets.UTF_8);
            sb.append(r[0]).append('\t').append(B64.encodeToString(body)).append('\t');
            try {
                Schedule s = Webhook.schedule(request(body));
                sb.append("OK\t").append(String.join(",", enc(s.jobId()), enc(s.jobCode()), enc(s.instanceId()),
                        inst(s.scheduledFor()), inst(s.firedAt()), enc(s.triggerKind()), enc(s.correlationId()),
                        enc(s.payloadJson()), Boolean.toString(s.tracksCompletion()),
                        s.timeoutSeconds() == null ? "~" : s.timeoutSeconds().toString(),
                        Boolean.toString(s.concurrent())));
            } catch (WebhookFormatException ex) {
                sb.append("ERR\t").append(ex.getMessage().replace('\n', ' ').replace('\t', ' '));
            }
            sb.append('\n');
        }
        Files.writeString(file, sb.toString());
    }

    private static void failTable(Path file) throws IOException {
        List<String> reasons = List.of("bad input", "said \"hi\" then \\ broke", "line1\nline2\ttabbed",
                "café ☃", "\u0000\u0001\u001f\u007f\u0080ÿ", "\b\f\r/<>&'", "😀",
                "￿", " x ", "~");
        StringBuilder sb = new StringBuilder("# Generated by tests/java/.../GoldenGen.java from Result.fail. Do not edit.\n"
                + "# reason(b64)\\tstatus\\tbody(b64)\n");
        for (String reason : reasons) {
            Result r = Result.fail(reason);
            sb.append(enc(reason)).append('\t').append(r.status()).append('\t')
                    .append(B64.encodeToString(r.body())).append('\n');
        }
        Files.writeString(file, sb.toString());
    }

    private static byte[] concat(String a, byte[] b, String c) {
        byte[] x = a.getBytes(StandardCharsets.UTF_8);
        byte[] z = c.getBytes(StandardCharsets.UTF_8);
        byte[] outb = new byte[x.length + b.length + z.length];
        System.arraycopy(x, 0, outb, 0, x.length);
        System.arraycopy(b, 0, outb, x.length, b.length);
        System.arraycopy(z, 0, outb, x.length + b.length, z.length);
        return outb;
    }
}
