// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * The platform's canonical error envelope (CONVENTIONS.md §4).
 */
export type ErrorResponse = {
    /**
     * the machine-readable error code
     */
    error: string;
    /**
     * a human-readable message
     */
    message: string;
    /**
     * optional structured detail; omitted when empty
     */
    details?: {
        [key: string]: unknown;
    };
};

export type CreateFunctionRequest = {
    applicationCode: string;
    serviceName: string;
    name: string;
    runtime: 'jvm' | 'wasm';
    description?: string;
    clientId?: string;
};

export type UpdateFunctionRequest = {
    description?: string;
    status?: 'ACTIVE' | 'DISABLED';
};

export type FunctionResponseLive = {
    version: number;
    versionId: string;
};

export type FunctionResponse = {
    id: string;
    address: string;
    applicationCode: string;
    serviceName: string;
    name: string;
    applicationId: string;
    clientId?: string;
    runtime: 'jvm' | 'wasm';
    description?: string;
    status: 'ACTIVE' | 'DISABLED';
    live?: FunctionResponseLive;
    createdAt: string;
    updatedAt: string;
};

/**
 * The offset-paginated envelope shared by every list route (apicommon.OffsetPage).
 */
export type FunctionPageResponse = {
    data: Array<FunctionResponse>;
    page: number;
    size: number;
    total: number;
    total_pages: number;
};

/**
 * A recorded publish signer identity (VersionResponse.SignerResponse / DesiredState.SignerView — same wire shape).
 */
export type SignerResponse = {
    issuer: string;
    subject: string;
};

/**
 * The publish-time manifest, as parsed by Manifest#parseStrict — only runtime/entrypoint are mandatory, everything else defaults.
 */
export type PublishManifestRequest = {
    runtime: 'jvm' | 'wasm';
    entrypoint: string;
    pool?: string;
    warm?: boolean;
    limits?: {
        maxDurationMs?: number;
        maxConcurrency?: number;
        wasmMemoryMb?: number;
    };
    endpoints?: Array<{
        path: string;
        auth: 'webhook' | 'platform' | 'none';
        methods?: Array<'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS'>;
        cors?: {
            origins?: Array<string>;
            methods?: Array<string>;
            headers?: Array<string>;
            allowCredentials?: boolean;
        };
        maxBodyBytes?: number;
        timeoutMs?: number;
    }>;
    subscriptions?: Array<{
        eventType: string;
        path: string;
        mode?: 'IMMEDIATE' | 'NEXT_ON_ERROR' | 'BLOCK_ON_ERROR';
        maxRetries?: number;
        timeoutSeconds?: number;
        dataOnly?: boolean;
    }>;
    schedules?: Array<{
        cron: string;
        timezone?: string;
        path: string;
        payload?: {
            [key: string]: unknown;
        };
    }>;
    public?: Array<{
        hostname: string;
        pathPrefix?: string;
        /**
         * opt-in alias name prefixes (each a DNS label, never 'live', no duplicates); absent/empty means exact-hostname match only
         */
        aliasPrefixes?: Array<string>;
    }>;
    config?: Array<string>;
    secrets?: Array<string>;
    db?: Array<{
        name: string;
        secretRef: string;
        poolSize?: number;
    }>;
    httpAllow?: Array<string>;
};

export type PublishRequest = {
    artifactRef: string;
    digest: string;
    signatureBundle?: string;
    manifest: PublishManifestRequest;
};

export type PublishResponse = {
    id: string;
    version: number;
    state: 'PUBLISHED';
    digest: string;
    signer?: SignerResponse;
};

export type UploadArtifactResponse = {
    artifactRef: string;
    digest: string;
    bytes: number;
};

export type ManifestLimits = {
    maxDurationMs: number;
    maxConcurrency: number;
    wasmMemoryMb?: number;
};

export type ManifestCors = {
    origins: Array<string>;
    methods: Array<string>;
    headers: Array<string>;
    allowCredentials: boolean;
};

export type ManifestEndpoint = {
    path: string;
    auth: 'webhook' | 'platform' | 'none';
    methods?: Array<'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS'>;
    cors?: ManifestCors;
    maxBodyBytes: number;
    timeoutMs: number;
};

export type ManifestSubscription = {
    eventType: string;
    path: string;
    mode: 'IMMEDIATE' | 'NEXT_ON_ERROR' | 'BLOCK_ON_ERROR';
    maxRetries: number;
    timeoutSeconds: number;
    dataOnly: boolean;
};

export type ManifestSchedule = {
    cron: string;
    timezone?: string;
    path: string;
    payload?: {
        [key: string]: unknown;
    };
};

export type ManifestPublicRoute = {
    hostname: string;
    pathPrefix: string;
    /**
     * opt-in alias name prefixes; [] when the route is exact-match only
     */
    aliasPrefixes?: Array<string>;
};

export type ManifestDbRef = {
    name: string;
    secretRef: string;
    poolSize: number;
};

/**
 * The resolved manifest as the server writes it back (Manifest#toJson) — every key always present.
 */
export type Manifest = {
    runtime: 'jvm' | 'wasm';
    entrypoint: string;
    pool: string;
    warm: boolean;
    limits: ManifestLimits;
    endpoints: Array<ManifestEndpoint>;
    subscriptions: Array<ManifestSubscription>;
    schedules: Array<ManifestSchedule>;
    public: Array<ManifestPublicRoute>;
    config: Array<string>;
    secrets: Array<string>;
    db: Array<ManifestDbRef>;
    httpAllow: Array<string>;
};

/**
 * The list shape omits `manifest`; the single-GET shape (`getFunctionVersion`) adds it.
 */
export type VersionResponse = {
    id: string;
    version: number;
    state: 'PUBLISHED' | 'READY' | 'RETIRED';
    digest: string;
    artifactRef: string;
    pool: string;
    warm: boolean;
    signer?: SignerResponse;
    publishedBy: string;
    publishedAt: string;
    readyAt?: string;
    retiredAt?: string;
    live: boolean;
    manifest?: Manifest;
};

export type PromoteRequest = {
    version: number;
};

export type PromoteResponse = {
    alias: string;
    version: number;
    versionId: string;
    previousVersion?: number;
};

/**
 * Body of POST manifest/check.
 */
export type CheckManifestRequest = {
    manifest: PublishManifestRequest;
    /**
     * defaults to `live` when absent/blank
     */
    alias?: string;
};

/**
 * One entry of CheckManifestResponse#errors — the same shape a real publish rejection's error body carries. A manifest-parse problem's details carries a pointer (RFC 6901 JSON Pointer, "" = the document root) to where in the manifest it is; a cross-check problem (event type not found, etc.) may carry other detail keys or none.
 */
export type ManifestErrorResponse = {
    code: string;
    message: string;
    details?: {
        /**
         * RFC 6901 JSON Pointer into the manifest document where this problem is; "" means the document root. Present on a manifest-parse problem, absent on most cross-check problems.
         */
        pointer?: string;
        [key: string]: unknown;
    };
};

/**
 * 200 body of POST manifest/check. valid is errors empty; plan is present only when valid.
 */
export type CheckManifestResponse = {
    valid: boolean;
    errors: Array<ManifestErrorResponse>;
    plan?: PromotePlanResponse;
};

export type PoolActionResponse = {
    action: 'create' | 'update' | 'unchanged';
    key: string;
    changedFields: Array<string>;
};

export type SubscriptionActionResponse = {
    action: 'create' | 'update' | 'delete' | 'unchanged';
    triggerKey: string;
    eventType: string;
    changedFields: Array<string>;
};

export type ScheduleActionResponse = {
    action: 'create' | 'update' | 'delete' | 'unchanged';
    triggerKey: string;
    cron: string;
    timezone?: string;
    changedFields: Array<string>;
};

export type RouteKeyResponse = {
    hostname: string;
    pathPrefix: string;
    aliasPrefixes: Array<string>;
};

export type PublicRoutesActionResponse = {
    action: 'replace' | 'unchanged';
    added: Array<RouteKeyResponse>;
    removed: Array<RouteKeyResponse>;
};

/**
 * What would make TriggerSync#apply of this plan fail — PUBLIC_ROUTE_TAKEN or TRIGGER_KEY_COLLISION.
 */
export type ConflictResponse = {
    code: string;
    message: string;
};

/**
 * PromotePlan on the wire. httpOnly is true for a named alias (function-zones-and-aliases.md §2) — pool/subscriptions/schedules/publicRoutes are then absent.
 */
export type PromotePlanResponse = {
    alias: string;
    /**
     * the alias's version before this promote; absent when the alias is unset
     */
    fromVersion?: number;
    toVersion: number;
    settingsMissing: Array<string>;
    httpOnly: boolean;
    pool?: PoolActionResponse;
    subscriptions?: Array<SubscriptionActionResponse>;
    schedules?: Array<ScheduleActionResponse>;
    publicRoutes?: PublicRoutesActionResponse;
    conflicts: Array<ConflictResponse>;
};

export type AliasResponse = {
    alias: string;
    version: number;
    versionId: string;
    updatedBy: string;
    updatedAt: string;
};

export type StatusResponseLive = {
    version: number;
};

export type StatusResponseVersionSummary = {
    version: number;
    state: 'PUBLISHED' | 'READY' | 'RETIRED';
};

export type StatusResponseLoadedSummary = {
    version: number;
    state: 'REGISTERED' | 'LOADED' | 'FAILED';
    error?: string;
};

export type StatusResponseHostSummary = {
    hostId: string;
    pool: string;
    state: 'ACTIVE' | 'DRAINING';
    lastHeartbeat: string;
    stale: boolean;
    loaded: Array<StatusResponseLoadedSummary>;
};

export type StatusResponseWiringEntry = {
    kind: 'POOL' | 'SUBSCRIPTION' | 'SCHEDULED_JOB';
    code: string;
    objectId: string;
    present: boolean;
};

export type StatusResponse = {
    address: string;
    status: 'ACTIVE' | 'DISABLED';
    live?: StatusResponseLive;
    versions: Array<StatusResponseVersionSummary>;
    hosts: Array<StatusResponseHostSummary>;
    wiring: Array<StatusResponseWiringEntry>;
};

export type PoolSummaryResponse = {
    pool: string;
    hosts: number;
};

/**
 * One manifest that contributed to `declared`/`missing`: `keys` is that manifest's own full key list, not only the keys it added beyond another entry.
 */
export type DeclaredByEntry = {
    version: number;
    keys: Array<string>;
};

export type ConfigResponse = {
    values: {
        [key: string]: string;
    };
    declared: Array<string>;
    missing: Array<string>;
    declaredBy: Array<DeclaredByEntry>;
};

export type SetConfigRequest = {
    values?: {
        [key: string]: string;
    };
};

export type SecretKeyResponse = {
    key: string;
    updatedAt: string;
    updatedBy: string;
};

export type SecretListResponse = {
    keys: Array<SecretKeyResponse>;
    declared: Array<string>;
    missing: Array<string>;
    declaredBy: Array<DeclaredByEntry>;
};

export type SetSecretRequest = {
    value?: string;
};

export type PolicySignerRequest = {
    issuer: string;
    subject: string;
    runtimes?: Array<'jvm' | 'wasm'>;
};

export type PolicyCeilingsRequest = {
    maxDurationMs?: number;
    maxConcurrency?: number;
    maxWasmMemoryMb?: number;
    maxDbPoolSize?: number;
};

export type PutPolicyRequest = {
    signers?: Array<PolicySignerRequest>;
    ceilings?: PolicyCeilingsRequest;
};

export type PolicySignerResponse = {
    issuer: string;
    subject: string;
    runtimes: Array<'jvm' | 'wasm'>;
};

export type PolicyCeilingsResponse = {
    maxDurationMs: number;
    maxConcurrency: number;
    maxWasmMemoryMb: number;
    maxDbPoolSize: number;
};

export type PolicyResponse = {
    owner: string;
    signers: Array<PolicySignerResponse>;
    ceilings: PolicyCeilingsResponse;
    stored: boolean;
    /**
     * absent on the effective-default shape, which has no stored row
     */
    updatedAt?: string;
};

export type PolicyListResponse = {
    policies: Array<PolicyResponse>;
};

export type ClaimRequest = {
    hostname: string;
    clientId?: string;
};

export type DomainResponse = {
    id: string;
    hostname: string;
    owner: string;
    createdAt: string;
};

export type FunctionRouteResponse = {
    hostname: string;
    pathPrefix: string;
    address: string;
    aliasPrefixes: Array<string>;
};

export type HeartbeatLoadedEntry = {
    address: string;
    version: number;
    state: 'REGISTERED' | 'LOADED' | 'FAILED';
    error?: string;
};

export type HeartbeatRequest = {
    hostId: string;
    pool: string;
    state: 'ACTIVE' | 'DRAINING';
    loaded?: Array<HeartbeatLoadedEntry>;
};

export type EmitEventItem = {
    type: string;
    subject?: string;
    dedupId: string;
    data: {
        [key: string]: unknown;
    };
    correlationId?: string;
    causationId?: string;
    messageGroup?: string;
};

export type EmitEventsRequest = {
    hostId: string;
    address: string;
    version?: number;
    events: Array<EmitEventItem>;
};

export type BatchResultItem = {
    id: string;
    status: 'SUCCESS';
    error?: string;
};

export type BatchResponse = {
    results: Array<BatchResultItem>;
};

export type DesiredStateUnloadEntry = {
    address: string;
    version: number;
};

export type DesiredStatePublicRouteEntry = {
    hostname: string;
    pathPrefix: string;
    address: string;
    aliasPrefixes: Array<string>;
};

export type DesiredStateFunctionEntry = {
    address: string;
    functionId: string;
    versionId: string;
    version: number;
    role: 'live' | 'candidate' | 'alias';
    mode: 'warm' | 'lazy';
    digest: string;
    artifactRef: string;
    signatureBundle?: string;
    manifest: Manifest;
    signer?: SignerResponse;
    webhookSigningSecret?: string;
    applicationId: string;
    clientId?: string;
    config: {
        [key: string]: string;
    };
    secrets: {
        [key: string]: string;
    };
    missingSettings: Array<string>;
    /**
     * the named (non-`live`) aliases pointing at this version, sorted; empty when none
     */
    aliases: Array<string>;
};

export type DesiredStateDocument = {
    pool: string;
    functions: Array<DesiredStateFunctionEntry>;
    unload: Array<DesiredStateUnloadEntry>;
    publicRoutes: Array<DesiredStatePublicRouteEntry>;
};

export type ListFunctionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * an address pattern filter
         */
        address?: string;
        /**
         * an owning client id, or `platform`
         */
        clientId?: string;
        /**
         * ACTIVE or DISABLED
         */
        status?: 'ACTIVE' | 'DISABLED';
        /**
         * 0-based page index
         */
        page?: number;
        /**
         * page size
         */
        size?: number;
    };
    url: '/api/functions';
};

export type ListFunctionsErrors = {
    /**
     * STATUS_INVALID, ADDRESS_PATTERN_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
};

export type ListFunctionsError = ListFunctionsErrors[keyof ListFunctionsErrors];

export type ListFunctionsResponses = {
    /**
     * A page of functions
     */
    200: FunctionPageResponse;
};

export type ListFunctionsResponse = ListFunctionsResponses[keyof ListFunctionsResponses];

export type CreateFunctionData = {
    body: CreateFunctionRequest;
    path?: never;
    query?: never;
    url: '/api/functions';
};

export type CreateFunctionErrors = {
    /**
     * APPLICATION_CODE_REQUIRED, RUNTIME_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * APPLICATION_CODE_NOT_ADDRESSABLE
     */
    404: ErrorResponse;
    /**
     * FUNCTION_EXISTS
     */
    409: ErrorResponse;
};

export type CreateFunctionError = CreateFunctionErrors[keyof CreateFunctionErrors];

export type CreateFunctionResponses = {
    /**
     * The created function
     */
    201: FunctionResponse;
};

export type CreateFunctionResponse = CreateFunctionResponses[keyof CreateFunctionResponses];

export type DeleteFunctionData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: never;
    url: '/api/functions/{address}';
};

export type DeleteFunctionErrors = {
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
};

export type DeleteFunctionError = DeleteFunctionErrors[keyof DeleteFunctionErrors];

export type DeleteFunctionResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteFunctionResponse = DeleteFunctionResponses[keyof DeleteFunctionResponses];

export type GetFunctionData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: never;
    url: '/api/functions/{address}';
};

export type GetFunctionErrors = {
    /**
     * ADDRESS_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
};

export type GetFunctionError = GetFunctionErrors[keyof GetFunctionErrors];

export type GetFunctionResponses = {
    /**
     * The function
     */
    200: FunctionResponse;
};

export type GetFunctionResponse = GetFunctionResponses[keyof GetFunctionResponses];

export type UpdateFunctionData = {
    body: UpdateFunctionRequest;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: never;
    url: '/api/functions/{address}';
};

export type UpdateFunctionErrors = {
    /**
     * FUNCTION_IMMUTABLE_FIELD, STATUS_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
};

export type UpdateFunctionError = UpdateFunctionErrors[keyof UpdateFunctionErrors];

export type UpdateFunctionResponses = {
    /**
     * Updated
     */
    204: void;
};

export type UpdateFunctionResponse = UpdateFunctionResponses[keyof UpdateFunctionResponses];

export type GetFunctionStatusData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: never;
    url: '/api/functions/{address}/status';
};

export type GetFunctionStatusErrors = {
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
};

export type GetFunctionStatusError = GetFunctionStatusErrors[keyof GetFunctionStatusErrors];

export type GetFunctionStatusResponses = {
    /**
     * The status
     */
    200: StatusResponse;
};

export type GetFunctionStatusResponse = GetFunctionStatusResponses[keyof GetFunctionStatusResponses];

export type ListFunctionPoolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/function-pools';
};

export type ListFunctionPoolsErrors = {
    /**
     * ANCHOR_REQUIRED, PERMISSION_REQUIRED
     */
    403: ErrorResponse;
};

export type ListFunctionPoolsError = ListFunctionPoolsErrors[keyof ListFunctionPoolsErrors];

export type ListFunctionPoolsResponses = {
    /**
     * The pools
     */
    200: Array<PoolSummaryResponse>;
};

export type ListFunctionPoolsResponse = ListFunctionPoolsResponses[keyof ListFunctionPoolsResponses];

export type ListFunctionVersionsData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: never;
    url: '/api/functions/{address}/versions';
};

export type ListFunctionVersionsErrors = {
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
};

export type ListFunctionVersionsError = ListFunctionVersionsErrors[keyof ListFunctionVersionsErrors];

export type ListFunctionVersionsResponses = {
    /**
     * The versions
     */
    200: Array<VersionResponse>;
};

export type ListFunctionVersionsResponse = ListFunctionVersionsResponses[keyof ListFunctionVersionsResponses];

export type PublishFunctionVersionData = {
    body: PublishRequest;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: never;
    url: '/api/functions/{address}/versions';
};

export type PublishFunctionVersionErrors = {
    /**
     * ARTIFACT_REF_REQUIRED, ARTIFACT_REF_INVALID, DIGEST_INVALID, MANIFEST_REQUIRED, MANIFEST_UNKNOWN_FIELD, MANIFEST_INVALID, RUNTIME_INVALID, RUNTIME_MISMATCH, ENTRYPOINT_REQUIRED, ENTRYPOINT_INVALID, POOL_INVALID, LIMIT_INVALID, LIMIT_OVER_CEILING, LIMIT_NOT_APPLICABLE, ENDPOINT_INVALID, ENDPOINT_AUTH_REQUIRED, ROUTE_AMBIGUOUS, SUBSCRIPTION_INVALID, SUBSCRIPTION_DUPLICATE, SUBSCRIPTION_PATH_NOT_WEBHOOK, SCHEDULE_INVALID, SCHEDULE_DUPLICATE, SCHEDULE_PATH_NOT_WEBHOOK, PUBLIC_ROUTE_INVALID, PUBLIC_ROUTE_DUPLICATE, DB_INVALID, CONFIG_INVALID, SIGNATURE_REQUIRED, SIGNATURE_REJECTED
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * FUNCTION_DISABLED, VERSION_DIGEST_EXISTS
     */
    409: ErrorResponse;
    /**
     * ARTIFACT_REF_MISMATCH, ARTIFACT_NOT_UPLOADED
     */
    422: ErrorResponse;
    /**
     * ARTIFACT_STORE_NOT_CONFIGURED
     */
    503: ErrorResponse;
};

export type PublishFunctionVersionError = PublishFunctionVersionErrors[keyof PublishFunctionVersionErrors];

export type PublishFunctionVersionResponses = {
    /**
     * The published version
     */
    201: PublishResponse;
};

export type PublishFunctionVersionResponse = PublishFunctionVersionResponses[keyof PublishFunctionVersionResponses];

export type CheckManifestData = {
    body: CheckManifestRequest;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: never;
    url: '/api/functions/{address}/manifest/check';
};

export type CheckManifestErrors = {
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
};

export type CheckManifestError = CheckManifestErrors[keyof CheckManifestErrors];

export type CheckManifestResponses = {
    /**
     * Always 200 once authorised and the function is reachable — `valid` says whether the manifest is publishable
     */
    200: CheckManifestResponse;
};

export type CheckManifestResponse2 = CheckManifestResponses[keyof CheckManifestResponses];

export type GetFunctionVersionData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
        /**
         * the version number
         */
        version: number;
    };
    query?: never;
    url: '/api/functions/{address}/versions/{version}';
};

export type GetFunctionVersionErrors = {
    /**
     * VERSION_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND, FunctionVersion_NOT_FOUND
     */
    404: ErrorResponse;
};

export type GetFunctionVersionError = GetFunctionVersionErrors[keyof GetFunctionVersionErrors];

export type GetFunctionVersionResponses = {
    /**
     * The version
     */
    200: VersionResponse;
};

export type GetFunctionVersionResponse = GetFunctionVersionResponses[keyof GetFunctionVersionResponses];

export type RetireFunctionVersionData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
        /**
         * the version number
         */
        version: number;
    };
    query?: never;
    url: '/api/functions/{address}/versions/{version}/retire';
};

export type RetireFunctionVersionErrors = {
    /**
     * VERSION_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND, FunctionVersion_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * VERSION_IS_LIVE, VERSION_ALIASED
     */
    409: ErrorResponse;
};

export type RetireFunctionVersionError = RetireFunctionVersionErrors[keyof RetireFunctionVersionErrors];

export type RetireFunctionVersionResponses = {
    /**
     * The retired version
     */
    200: VersionResponse;
};

export type RetireFunctionVersionResponse = RetireFunctionVersionResponses[keyof RetireFunctionVersionResponses];

export type DeleteFunctionAliasData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
        /**
         * the alias name to remove
         */
        alias: string;
    };
    query?: never;
    url: '/api/functions/{address}/aliases/{alias}';
};

export type DeleteFunctionAliasErrors = {
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND, Alias_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * ALIAS_PROTECTED
     */
    409: ErrorResponse;
};

export type DeleteFunctionAliasError = DeleteFunctionAliasErrors[keyof DeleteFunctionAliasErrors];

export type DeleteFunctionAliasResponses = {
    /**
     * Removed
     */
    204: void;
};

export type DeleteFunctionAliasResponse = DeleteFunctionAliasResponses[keyof DeleteFunctionAliasResponses];

export type PromoteFunctionAliasData = {
    body: PromoteRequest;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
        /**
         * the alias name — `live`, or any name matching `^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$`
         */
        alias: string;
    };
    query?: never;
    url: '/api/functions/{address}/aliases/{alias}';
};

export type PromoteFunctionAliasErrors = {
    /**
     * ALIAS_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND, FunctionVersion_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * VERSION_NOT_READY, VERSION_RETIRED, FUNCTION_DISABLED, ALIAS_UNCHANGED, SETTINGS_MISSING
     */
    409: ErrorResponse;
};

export type PromoteFunctionAliasError = PromoteFunctionAliasErrors[keyof PromoteFunctionAliasErrors];

export type PromoteFunctionAliasResponses = {
    /**
     * The promotion result
     */
    200: PromoteResponse;
};

export type PromoteFunctionAliasResponse = PromoteFunctionAliasResponses[keyof PromoteFunctionAliasResponses];

export type ListFunctionAliasesData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: never;
    url: '/api/functions/{address}/aliases';
};

export type ListFunctionAliasesErrors = {
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
};

export type ListFunctionAliasesError = ListFunctionAliasesErrors[keyof ListFunctionAliasesErrors];

export type ListFunctionAliasesResponses = {
    /**
     * The aliases
     */
    200: Array<AliasResponse>;
};

export type ListFunctionAliasesResponse = ListFunctionAliasesResponses[keyof ListFunctionAliasesResponses];

export type UploadFunctionArtifactData = {
    body: Blob | File;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
        /**
         * the `sha256:<hex>` digest of the uploaded bytes
         */
        digest: string;
    };
    query?: never;
    url: '/api/functions/{address}/artifacts/{digest}';
};

export type UploadFunctionArtifactErrors = {
    /**
     * DIGEST_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * ARTIFACT_TOO_LARGE
     */
    413: ErrorResponse;
    /**
     * ARTIFACT_EMPTY, DIGEST_MISMATCH
     */
    422: ErrorResponse;
    /**
     * ARTIFACT_STORE_NOT_CONFIGURED
     */
    503: ErrorResponse;
};

export type UploadFunctionArtifactError = UploadFunctionArtifactErrors[keyof UploadFunctionArtifactErrors];

export type UploadFunctionArtifactResponses = {
    /**
     * The stored artifact
     */
    200: UploadArtifactResponse;
};

export type UploadFunctionArtifactResponse = UploadFunctionArtifactResponses[keyof UploadFunctionArtifactResponses];

export type GetFunctionConfigData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: {
        /**
         * the version whose declared keys join the live manifest's; absent defaults to the newest non-retired version
         */
        version?: number;
    };
    url: '/api/functions/{address}/config';
};

export type GetFunctionConfigErrors = {
    /**
     * VERSION_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND, FunctionVersion_NOT_FOUND
     */
    404: ErrorResponse;
};

export type GetFunctionConfigError = GetFunctionConfigErrors[keyof GetFunctionConfigErrors];

export type GetFunctionConfigResponses = {
    /**
     * The config
     */
    200: ConfigResponse;
};

export type GetFunctionConfigResponse = GetFunctionConfigResponses[keyof GetFunctionConfigResponses];

export type SetFunctionConfigData = {
    body: SetConfigRequest;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: {
        /**
         * the version whose declared keys join the live manifest's in the response; absent defaults to the newest non-retired version
         */
        version?: number;
    };
    url: '/api/functions/{address}/config';
};

export type SetFunctionConfigErrors = {
    /**
     * SETTING_KEY_INVALID, SETTING_TOO_LARGE, VERSION_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND, FunctionVersion_NOT_FOUND
     */
    404: ErrorResponse;
};

export type SetFunctionConfigError = SetFunctionConfigErrors[keyof SetFunctionConfigErrors];

export type SetFunctionConfigResponses = {
    /**
     * The config
     */
    200: ConfigResponse;
};

export type SetFunctionConfigResponse = SetFunctionConfigResponses[keyof SetFunctionConfigResponses];

export type ListFunctionSecretsData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
    };
    query?: {
        /**
         * the version whose declared keys join the live manifest's; absent defaults to the newest non-retired version
         */
        version?: number;
    };
    url: '/api/functions/{address}/secrets';
};

export type ListFunctionSecretsErrors = {
    /**
     * VERSION_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND, FunctionVersion_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * ENCRYPTION_UNCONFIGURED
     */
    503: ErrorResponse;
};

export type ListFunctionSecretsError = ListFunctionSecretsErrors[keyof ListFunctionSecretsErrors];

export type ListFunctionSecretsResponses = {
    /**
     * The secret keys
     */
    200: SecretListResponse;
};

export type ListFunctionSecretsResponse = ListFunctionSecretsResponses[keyof ListFunctionSecretsResponses];

export type DeleteFunctionSecretData = {
    body?: never;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
        /**
         * the config/secret key
         */
        key: string;
    };
    query?: never;
    url: '/api/functions/{address}/secrets/{key}';
};

export type DeleteFunctionSecretErrors = {
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND, FunctionSecret_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * ENCRYPTION_UNCONFIGURED
     */
    503: ErrorResponse;
};

export type DeleteFunctionSecretError = DeleteFunctionSecretErrors[keyof DeleteFunctionSecretErrors];

export type DeleteFunctionSecretResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteFunctionSecretResponse = DeleteFunctionSecretResponses[keyof DeleteFunctionSecretResponses];

export type SetFunctionSecretData = {
    body: SetSecretRequest;
    path: {
        /**
         * the function's `application.service.name` address
         */
        address: string;
        /**
         * the config/secret key
         */
        key: string;
    };
    query?: never;
    url: '/api/functions/{address}/secrets/{key}';
};

export type SetFunctionSecretErrors = {
    /**
     * SETTING_KEY_INVALID, SETTING_VALUE_REQUIRED, SETTING_TOO_LARGE
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * ENCRYPTION_UNCONFIGURED
     */
    503: ErrorResponse;
};

export type SetFunctionSecretError = SetFunctionSecretErrors[keyof SetFunctionSecretErrors];

export type SetFunctionSecretResponses = {
    /**
     * Set
     */
    204: void;
};

export type SetFunctionSecretResponse = SetFunctionSecretResponses[keyof SetFunctionSecretResponses];

export type ListFunctionPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/function-policies';
};

export type ListFunctionPoliciesErrors = {
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
};

export type ListFunctionPoliciesError = ListFunctionPoliciesErrors[keyof ListFunctionPoliciesErrors];

export type ListFunctionPoliciesResponses = {
    /**
     * The stored policies, platform first then client ids ascending
     */
    200: PolicyListResponse;
};

export type ListFunctionPoliciesResponse = ListFunctionPoliciesResponses[keyof ListFunctionPoliciesResponses];

export type GetFunctionPolicyData = {
    body?: never;
    path: {
        /**
         * a client id, or the literal `platform`
         */
        owner: string;
    };
    query?: never;
    url: '/api/function-policies/{owner}';
};

export type GetFunctionPolicyErrors = {
    /**
     * OWNER_REQUIRED
     */
    400: ErrorResponse;
    /**
     * ANCHOR_REQUIRED, PERMISSION_REQUIRED
     */
    403: ErrorResponse;
};

export type GetFunctionPolicyError = GetFunctionPolicyErrors[keyof GetFunctionPolicyErrors];

export type GetFunctionPolicyResponses = {
    /**
     * The policy
     */
    200: PolicyResponse;
};

export type GetFunctionPolicyResponse = GetFunctionPolicyResponses[keyof GetFunctionPolicyResponses];

export type PutFunctionPolicyData = {
    body: PutPolicyRequest;
    path: {
        /**
         * a client id, or the literal `platform`
         */
        owner: string;
    };
    query?: never;
    url: '/api/function-policies/{owner}';
};

export type PutFunctionPolicyErrors = {
    /**
     * SIGNER_INVALID, SIGNER_DUPLICATE, RUNTIME_INVALID, CEILING_INVALID
     */
    400: ErrorResponse;
    /**
     * ANCHOR_REQUIRED, PERMISSION_REQUIRED
     */
    403: ErrorResponse;
};

export type PutFunctionPolicyError = PutFunctionPolicyErrors[keyof PutFunctionPolicyErrors];

export type PutFunctionPolicyResponses = {
    /**
     * The policy
     */
    200: PolicyResponse;
};

export type PutFunctionPolicyResponse = PutFunctionPolicyResponses[keyof PutFunctionPolicyResponses];

export type ListFunctionDomainsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * an owning client id, or `platform`
         */
        clientId: string;
    };
    url: '/api/function-domains';
};

export type ListFunctionDomainsErrors = {
    /**
     * CLIENT_ID_REQUIRED
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
};

export type ListFunctionDomainsError = ListFunctionDomainsErrors[keyof ListFunctionDomainsErrors];

export type ListFunctionDomainsResponses = {
    /**
     * The domains
     */
    200: Array<DomainResponse>;
};

export type ListFunctionDomainsResponse = ListFunctionDomainsResponses[keyof ListFunctionDomainsResponses];

export type ClaimFunctionDomainData = {
    body: ClaimRequest;
    path?: never;
    query?: never;
    url: '/api/function-domains';
};

export type ClaimFunctionDomainErrors = {
    /**
     * HOSTNAME_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * DOMAIN_TAKEN — an existing claim (any owner) equals, covers, or is covered by this hostname
     */
    409: ErrorResponse;
};

export type ClaimFunctionDomainError = ClaimFunctionDomainErrors[keyof ClaimFunctionDomainErrors];

export type ClaimFunctionDomainResponses = {
    /**
     * The claimed domain
     */
    201: DomainResponse;
};

export type ClaimFunctionDomainResponse = ClaimFunctionDomainResponses[keyof ClaimFunctionDomainResponses];

export type ReleaseFunctionDomainData = {
    body?: never;
    path: {
        /**
         * any hostname covered by the claimed zone, or the zone apex itself — resolves to the zone's one claim
         */
        hostname: string;
    };
    query?: never;
    url: '/api/function-domains/{hostname}';
};

export type ReleaseFunctionDomainErrors = {
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * FunctionDomain_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * DOMAIN_IN_USE — a public route exists on this zone's apex or on a hostname covered by it
     */
    409: ErrorResponse;
};

export type ReleaseFunctionDomainError = ReleaseFunctionDomainErrors[keyof ReleaseFunctionDomainErrors];

export type ReleaseFunctionDomainResponses = {
    /**
     * Released
     */
    204: void;
};

export type ReleaseFunctionDomainResponse = ReleaseFunctionDomainResponses[keyof ReleaseFunctionDomainResponses];

export type GetFunctionDomainData = {
    body?: never;
    path: {
        /**
         * any hostname covered by a claimed zone, or the zone apex itself — resolves to the zone's one claim
         */
        hostname: string;
    };
    query?: never;
    url: '/api/function-domains/{hostname}';
};

export type GetFunctionDomainErrors = {
    /**
     * HOSTNAME_INVALID
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * FunctionDomain_NOT_FOUND
     */
    404: ErrorResponse;
};

export type GetFunctionDomainError = GetFunctionDomainErrors[keyof GetFunctionDomainErrors];

export type GetFunctionDomainResponses = {
    /**
     * The domain
     */
    200: DomainResponse;
};

export type GetFunctionDomainResponse = GetFunctionDomainResponses[keyof GetFunctionDomainResponses];

export type ListFunctionRoutesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * list every route for this hostname
         */
        hostname?: string;
        /**
         * list this one function's routes
         */
        address?: string;
    };
    url: '/api/function-routes';
};

export type ListFunctionRoutesErrors = {
    /**
     * FUNCTION_ROUTE_FILTER_REQUIRED
     */
    400: ErrorResponse;
    /**
     * PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * Function_NOT_FOUND
     */
    404: ErrorResponse;
};

export type ListFunctionRoutesError = ListFunctionRoutesErrors[keyof ListFunctionRoutesErrors];

export type ListFunctionRoutesResponses = {
    /**
     * The routes
     */
    200: Array<FunctionRouteResponse>;
};

export type ListFunctionRoutesResponse = ListFunctionRoutesResponses[keyof ListFunctionRoutesResponses];

export type GetDesiredStateData = {
    body?: never;
    path?: never;
    query: {
        /**
         * the host's own pool
         */
        pool: string;
    };
    url: '/control/functions/desired-state';
};

export type GetDesiredStateErrors = {
    /**
     * POOL_INVALID
     */
    400: ErrorResponse;
    /**
     * UNAUTHORIZED
     */
    401: ErrorResponse;
    /**
     * ANCHOR_REQUIRED, PERMISSION_REQUIRED
     */
    403: ErrorResponse;
};

export type GetDesiredStateError = GetDesiredStateErrors[keyof GetDesiredStateErrors];

export type GetDesiredStateResponses = {
    /**
     * The desired-state document
     */
    200: DesiredStateDocument;
};

export type GetDesiredStateResponse = GetDesiredStateResponses[keyof GetDesiredStateResponses];

export type HeartbeatFunctionHostData = {
    body: HeartbeatRequest;
    path?: never;
    query?: never;
    url: '/control/functions/heartbeat';
};

export type HeartbeatFunctionHostErrors = {
    /**
     * HOST_ID_INVALID, POOL_INVALID, HOST_STATE_INVALID, LOADED_INVALID
     */
    400: ErrorResponse;
    /**
     * UNAUTHORIZED
     */
    401: ErrorResponse;
    /**
     * ANCHOR_REQUIRED, PERMISSION_REQUIRED
     */
    403: ErrorResponse;
};

export type HeartbeatFunctionHostError = HeartbeatFunctionHostErrors[keyof HeartbeatFunctionHostErrors];

export type HeartbeatFunctionHostResponses = {
    /**
     * Recorded
     */
    204: void;
};

export type HeartbeatFunctionHostResponse = HeartbeatFunctionHostResponses[keyof HeartbeatFunctionHostResponses];

export type EmitFunctionEventsData = {
    body: EmitEventsRequest;
    path?: never;
    query?: never;
    url: '/control/functions/events';
};

export type EmitFunctionEventsErrors = {
    /**
     * BATCH_SIZE_INVALID, DEDUP_ID_REQUIRED, DEDUP_ID_DUPLICATE, EVENT_DATA_INVALID, EVENT_DATA_TOO_LARGE
     */
    400: ErrorResponse;
    /**
     * UNAUTHORIZED
     */
    401: ErrorResponse;
    /**
     * ANCHOR_REQUIRED, PERMISSION_REQUIRED, EVENT_TYPE_NOT_OWNED
     */
    403: ErrorResponse;
    /**
     * HOST_UNKNOWN, FUNCTION_NOT_SERVED_BY_HOST
     */
    409: ErrorResponse;
};

export type EmitFunctionEventsError = EmitFunctionEventsErrors[keyof EmitFunctionEventsErrors];

export type EmitFunctionEventsResponses = {
    /**
     * Per-event results
     */
    201: BatchResponse;
};

export type EmitFunctionEventsResponse = EmitFunctionEventsResponses[keyof EmitFunctionEventsResponses];

export type DownloadFunctionArtifactData = {
    body?: never;
    path: {
        /**
         * the function version's id
         */
        versionId: string;
    };
    query?: never;
    url: '/control/functions/artifacts/{versionId}';
};

export type DownloadFunctionArtifactErrors = {
    /**
     * UNAUTHORIZED
     */
    401: ErrorResponse;
    /**
     * ANCHOR_REQUIRED, PERMISSION_REQUIRED
     */
    403: ErrorResponse;
    /**
     * FunctionVersion_NOT_FOUND
     */
    404: ErrorResponse;
    /**
     * ARTIFACT_STORE_NOT_CONFIGURED
     */
    503: ErrorResponse;
};

export type DownloadFunctionArtifactError = DownloadFunctionArtifactErrors[keyof DownloadFunctionArtifactErrors];

export type DownloadFunctionArtifactResponses = {
    /**
     * The artifact bytes
     */
    200: Blob | File;
};

export type DownloadFunctionArtifactResponse = DownloadFunctionArtifactResponses[keyof DownloadFunctionArtifactResponses];
