//! Set / rotate and revoke a developer credential (Go
//! `SetDeveloperCredential`, `RevokeDeveloperCredential`). The handler
//! applies the coarse gate (self with the self-service permission, or a
//! user-write permission); `authorize` checks the target is within reach,
//! `execute` its kind, and the unit of work commits.

use std::sync::Arc;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use super::events::{DeveloperCredentialRevoked, DeveloperCredentialSet};
use super::{DeveloperCredential, DEVELOPER_ROLE};
use crate::principal::repository::PrincipalRepository;
use fc_platform_core::permissions;
use fc_platform_core::principal_kind::UserScope;
use fc_platform_core::shared::error::PlatformError;
use fc_platform_core::usecase::AuditMasked;
use fc_platform_core::usecase::Caller;
use fc_platform_core::usecase::{
    Committed, ExecutionContext, OrNotFound, UnitOfWork, UseCase, UseCaseError,
};

/// Set or rotate `principal_id`'s developer secret to `secret_ref` (the
/// keyed hash; generated by the handler, which answers the plaintext once).
/// The audit row records `{principalId}` only.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SetDeveloperCredentialCommand {
    pub principal_id: String,
    #[serde(skip)]
    pub secret_ref: String,
}

impl AuditMasked for SetDeveloperCredentialCommand {}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RevokeDeveloperCredentialCommand {
    pub principal_id: String,
}

impl AuditMasked for RevokeDeveloperCredentialCommand {}

/// The developer-credential target's reach (Go
/// `requireDeveloperCredentialAccess`'s post-load half): your own
/// credential always; someone else's only for a user you administer (a
/// client administrator: CLIENT-tier users of a client it holds, 403
/// otherwise; out of reach answers `User_NOT_FOUND`, as a missing id).
async fn require_credential_target(
    principals: &PrincipalRepository,
    caller: &Caller,
    id: &str,
) -> Result<(), UseCaseError> {
    let p = principals
        .find_by_id(id)
        .await?
        .ok_or_else(|| UseCaseError::verbatim(PlatformError::not_found("User", id)))?;
    if caller.principal_id() == Some(p.id.as_str()) {
        return Ok(());
    }
    if !caller.is_anchor() && p.scope != UserScope::Client {
        return Err(UseCaseError::verbatim(PlatformError::forbidden(
            "Client administrators can only manage client-scope users",
        )));
    }
    let in_scope = match p.client_id.as_deref() {
        Some(client_id) => caller.can_access_client(client_id),
        None => caller.is_anchor() || caller.has_permission(permissions::ADMIN_ALL),
    };
    if !in_scope {
        return Err(UseCaseError::verbatim(PlatformError::not_found("User", id)));
    }
    Ok(())
}

fn require_id(id: &str) -> Result<(), UseCaseError> {
    if id.trim().is_empty() {
        return Err(UseCaseError::validation(
            "PRINCIPAL_ID_REQUIRED",
            "Principal ID is required",
        ));
    }
    Ok(())
}

pub struct SetDeveloperCredentialUseCase<U: UnitOfWork> {
    principal_repo: Arc<PrincipalRepository>,
    unit_of_work: Arc<U>,
}

impl<U: UnitOfWork> SetDeveloperCredentialUseCase<U> {
    pub fn new(principal_repo: Arc<PrincipalRepository>, unit_of_work: Arc<U>) -> Self {
        Self {
            principal_repo,
            unit_of_work,
        }
    }
}

#[async_trait]
impl<U: UnitOfWork> UseCase for SetDeveloperCredentialUseCase<U> {
    type Command = SetDeveloperCredentialCommand;
    type Event = DeveloperCredentialSet;

    async fn validate(&self, command: &Self::Command) -> Result<(), UseCaseError> {
        require_id(&command.principal_id)
    }

    /// The target must be the caller or a user it administers (see
    /// `require_credential_target`); Go checks this post-load too.
    async fn authorize(
        &self,
        command: &SetDeveloperCredentialCommand,
        ctx: &ExecutionContext,
    ) -> Result<(), UseCaseError> {
        require_credential_target(&self.principal_repo, ctx.caller(), &command.principal_id).await
    }

    async fn execute(
        &self,
        command: Self::Command,
        ctx: ExecutionContext,
    ) -> Result<Committed<Self::Event>, UseCaseError> {
        let principal = match self
            .principal_repo
            .find_by_id(&command.principal_id)
            .await
            .or_not_found(
                "USER_NOT_FOUND",
                format!("User '{}' not found", command.principal_id),
            ) {
            Ok(p) => p,
            Err(e) => return Err(e),
        };
        if !principal.is_user() {
            return Err(UseCaseError::business_rule(
                "NOT_A_USER",
                "Developer credentials can only be set on USER type principals",
            ));
        }
        if !principal.roles.iter().any(|r| r.role == DEVELOPER_ROLE) {
            return Err(UseCaseError::business_rule(
                "NOT_A_DEVELOPER",
                "Principal does not hold the developer role",
            ));
        }
        let credential = DeveloperCredential {
            principal_id: principal.id.to_string(),
            secret_ref: Some(command.secret_ref.clone()),
        };
        let event = DeveloperCredentialSet::new(&ctx, principal.id.as_str());
        self.unit_of_work
            .commit(&credential, &*self.principal_repo, event, &command)
            .await
    }
}

pub struct RevokeDeveloperCredentialUseCase<U: UnitOfWork> {
    principal_repo: Arc<PrincipalRepository>,
    unit_of_work: Arc<U>,
}

impl<U: UnitOfWork> RevokeDeveloperCredentialUseCase<U> {
    pub fn new(principal_repo: Arc<PrincipalRepository>, unit_of_work: Arc<U>) -> Self {
        Self {
            principal_repo,
            unit_of_work,
        }
    }
}

#[async_trait]
impl<U: UnitOfWork> UseCase for RevokeDeveloperCredentialUseCase<U> {
    type Command = RevokeDeveloperCredentialCommand;
    type Event = DeveloperCredentialRevoked;

    async fn validate(&self, command: &Self::Command) -> Result<(), UseCaseError> {
        require_id(&command.principal_id)
    }

    /// The target must be the caller or a user it administers (see
    /// `require_credential_target`); Go checks this post-load too.
    async fn authorize(
        &self,
        command: &RevokeDeveloperCredentialCommand,
        ctx: &ExecutionContext,
    ) -> Result<(), UseCaseError> {
        require_credential_target(&self.principal_repo, ctx.caller(), &command.principal_id).await
    }

    async fn execute(
        &self,
        command: Self::Command,
        ctx: ExecutionContext,
    ) -> Result<Committed<Self::Event>, UseCaseError> {
        let principal = match self
            .principal_repo
            .find_by_id(&command.principal_id)
            .await
            .or_not_found(
                "USER_NOT_FOUND",
                format!("User '{}' not found", command.principal_id),
            ) {
            Ok(p) => p,
            Err(e) => return Err(e),
        };
        let credential = DeveloperCredential {
            principal_id: principal.id.to_string(),
            secret_ref: None,
        };
        let event = DeveloperCredentialRevoked::new(&ctx, principal.id.as_str());
        self.unit_of_work
            .commit_delete(&credential, &*self.principal_repo, event, &command)
            .await
    }
}
